FROM python:3.11-slim

WORKDIR /app
COPY ./app ./app

RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev && \
    pip install --no-cache-dir fastapi uvicorn[standard] pydantic psycopg2-binary requests

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]